### ISSUE TITLE
Suggestion about the mnist example

### ISSUE THREAD

**Issue by linzzzzzz** [facebookresearch/jacobian_regularizer#1]
Thanks for the nice work!

Just a suggestion about the code of mnist example.

From line 95 - 97, I guess it's better to write in the following way?

        loss_super_avg += loss_super.data*targets.size(0)
        loss_JR_avg += loss_JR.data*targets.size(0)
        loss_avg += loss.data*targets.size(0)

The original code would require a lot more unnecessary memory.

**Comment by shoyaida** [comment]
Thank you very much for catching that memory-growth bug! We have fixed it [with .item() rather than .data in order to keep it a bit more uniform with the training part of the code].
